### ISSUE TITLE
Support IPC read from Feather file with lz4?

### ISSUE THREAD

**Issue by brendan-ward** [kylebarron/arro3#186]
I tried to use `read_ipc` to read a Feather file created with the default lz4 compression (created via pandas), but bumped into this error:

```
Exception: C Data interface error: Invalid argument error: lz4 IPC decompression requires the lz4 feature
```

Is it possible pull in this optional feature for the `arrow-ipc` crate?

**Comment by kylebarron** [comment]
Oh, sorry I thought this was already activated! I'm traveling but when I get to my computer later today I'll check and add a test for this.

**Comment by kylebarron** [comment]
0.3.1 is building and pushing now

**Comment by brendan-ward** [comment]
Works great - thank you for adding so quickly!
