### ISSUE TITLE
pyo3-arrow - support version 53?

### ISSUE THREAD

**Issue by kevinli1993** [kylebarron/arro3#196]
Hi, thanks for maintaining this package! 

I have a couple questions: 

* It seems the latest version on [crates.io](https://crates.io/crates/pyo3-arrow/0.2.1/dependencies) has a dependency on arrow 52, even though the workspace itself seems to support arrow 53.  I'm not a Rust expert, so I'm not sure if this is expected?

* The line below in `Cargo.toml` suggests the version if 0.2.0. However, the crates.io version is 0.2.1.  Does `Cargo.toml` need to be bumped? 
https://github.com/kylebarron/arro3/blob/a81ac6efb89c5c13f058e7821088b020c7cbd5bc/pyo3-arrow/Cargo.toml#L3

Thanks!

**Comment by kylebarron** [comment]
Closed by https://github.com/kylebarron/arro3/pull/197

Published pyo3-arrow 0.3.0: https://crates.io/crates/pyo3-arrow
