### ISSUE TITLE
Expose arrow-avro

### ISSUE THREAD

**Issue by woile** [kylebarron/arro3#201]
Hi! This library looks great! I was wondering if you are planning to include [arrow-avro](https://github.com/apache/arrow-rs/tree/master/arrow-avro)

Thanks!

**Comment by kylebarron** [comment]
I've never used Avro and am not familiar with it. It could be in-scope to include in this library, but the arrow-avro crate is still under development and has not yet been published: https://docs.rs/arrow-avro/latest/arrow_avro/reader/index.html (an empty crate)

**Comment by woile** [comment]
Oh I feel like a fool haha apologies! let's review this ticket again when there's an actual implementation
