### ISSUE TITLE
Segmentation Fault after passing numpy-backed `arro3.core.Array` to `pyarrow.Array` at Interpreter Exit

### ISSUE THREAD

**Issue by 3ok** [kylebarron/arro3#230]
Hi,

I was trying to compare the performance of converting a numpy array to an arrow array via `pyarrow` or `arro3-core>=0.4.0`, but noticed there was a panic/segmentation fault at interpreter exit.

Here are my dependencies
```shell
$ pip list
Package    Version
---------- -------
arro3-core 0.4.1
numpy      2.1.2
pip        22.0.2
pyarrow    17.0.0
setuptools 59.6.0
```
Here is my script
```python
import time

import arro3.core
import numpy as np
import pyarrow as pa

N = 10_000_000
vec_np = np.random.randint(low=0, high=10_000, size=N)

start = time.perf_counter()
res_pa = pa.array(vec_np)
print(f"Time taken by pyarrow: {time.perf_counter() - start:.5f} seconds")

start = time.perf_counter()
res_arro3 = pa.array(arro3.core.Array.from_numpy(vec_np))
print(f"Time taken by arro3-core: {time.perf_counter() - start:.5f} seconds (nice)")

print("done")
```
and here is the output
```shell
$ RUST_BACKTRACE=1 python main.py 
Time taken by pyarrow: 0.00621 seconds
Time taken by arro3-core: 0.00007 seconds (nice)
done
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/gil.rs:201:21:
assertion `left != right` failed: The Python interpreter is not initialized and the `auto-initialize` feature is not enabled.

Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.
  left: 0
 right: 0
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: parking_lot::once::Once::call_once_slow
   5: pyo3::gil::GILGuard::acquire
   6: core::ptr::drop_in_place<pyo3::buffer::PyBuffer<i8>>
   7: alloc::sync::Arc<T,A>::drop_slow
   8: alloc::sync::Arc<T,A>::drop_slow
   9: core::ptr::drop_in_place<alloc::vec::Vec<core::option::Option<arrow_buffer::buffer::immutable::Buffer>>>
  10: arrow_data::ffi::release_array
  11: _ZNSt23_Sp_counted_ptr_inplaceIN5arrow12_GLOBAL__N_117ImportedArrayDataESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  12: _ZNSt23_Sp_counted_ptr_inplaceIN5arrow12_GLOBAL__N_114ImportedBufferESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  13: _ZNSt23_Sp_counted_ptr_inplaceIN5arrow9ArrayDataESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  14: _ZN5arrow12NumericArrayINS_9Int64TypeEED2Ev
  15: _ZL36__pyx_tp_dealloc_7pyarrow_3lib_ArrayP7_object
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: Py_FinalizeEx
  22: Py_RunMain
  23: Py_BytesMain
  24: <unknown>
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7fda31611d01 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
   1:     0x7fda3153af3b - core::fmt::write::h4b5a1270214bc4a7
   2:     0x7fda316169b3 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
   3:     0x7fda31617537 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   4:     0x7fda31616ec2 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   5:     0x7fda31616e59 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   6:     0x7fda31616e44 - rust_begin_unwind
   7:     0x7fda31120614 - core::panicking::panic_nounwind_fmt::h4c4dc67d0bbc166c
   8:     0x7fda3112067c - core::panicking::panic_nounwind::hb98133c151c787e4
   9:     0x7fda31120629 - core::panicking::panic_cannot_unwind::he9511e6e72319a3e
  10:     0x7fda3143712c - arrow_data::ffi::release_array::h6a0efa4ffb11fd74
  11:     0x7fda048e8713 - _ZNSt23_Sp_counted_ptr_inplaceIN5arrow12_GLOBAL__N_117ImportedArrayDataESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  12:     0x7fda048ea8a2 - _ZNSt23_Sp_counted_ptr_inplaceIN5arrow12_GLOBAL__N_114ImportedBufferESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  13:     0x7fda0853a2d3 - _ZNSt23_Sp_counted_ptr_inplaceIN5arrow9ArrayDataESaIvELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
  14:     0x7fda079c13b1 - _ZN5arrow12NumericArrayINS_9Int64TypeEED2Ev
  15:     0x7fda08809c03 - _ZL36__pyx_tp_dealloc_7pyarrow_3lib_ArrayP7_object
  16:     0x55b627154841 - <unknown>
  17:     0x55b62715463c - <unknown>
  18:     0x55b6272826c4 - <unknown>
  19:     0x55b62714605f - <unknown>
  20:     0x55b6272821d6 - <unknown>
  21:     0x55b62727ecd8 - Py_FinalizeEx
  22:     0x55b627270183 - Py_RunMain
  23:     0x55b62724670d - Py_BytesMain
  24:     0x7fda31b32d90 - <unknown>
  25:     0x7fda31b32e40 - __libc_start_main
  26:     0x55b627246605 - _start
  27:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```
I tried enabling the `auto-initialize` feature in the crates as suggested in the backtraces, and rebuild from source, but I got a segfault instead.

Note that this only happens when I try to convert a `arro3.core.Array` to a `pyarrow.Array` via the `pa.array(...)` _constructor_.

**Comment by kylebarron** [comment]
Thanks for the repro! I'm looking forward to digging into this, even though this is somewhat out of my wheel house.

This almost certainly is an issue in my zero copy numpy integration, because it's passing the numpy backed memory from numpy to arrow rust to pyarrow, and there's probably an issue in how that release callback works

**Comment by kylebarron** [comment]
**This gives a segmentation fault**

```py
import numpy as np
import pyarrow as pa
from arro3.core import Array

numpy_arr = np.array([0, 1, 2, 3], dtype=np.float64)
arro3_arr = Array(numpy_arr)
pyarrow_arr = pa.array(arro3_arr)
```

**This is fine** (not passing to pyarrow)

```py
import numpy as np
from arro3.core import Array

numpy_arr = np.array([0, 1, 2, 3], dtype=np.float64)
arro3_arr = Array(numpy_arr)
```

**This is fine** (not using numpy-backed array)

```py
import pyarrow as pa
from arro3.core import Array, DataType

arro3_arr = Array([0, 1, 2, 3], type=DataType.int8())
pyarrow_arr = pa.array(arro3_arr)
```

**Comment by kylebarron** [comment]
**This is fine** (manually calling `del` before Python interpreter exit)

```py
import numpy as np
import pyarrow as pa
from arro3.core import Array

numpy_arr = np.array([0, 1, 2, 3], dtype=np.float64)
arro3_arr = Array(numpy_arr)
pa_arr = pa.array(arro3_arr)
del pa_arr
```

**Comment by kylebarron** [comment]
It's erroring on [this line](https://github.com/PyO3/pyo3/blob/cd5369c1a0d264db5db030bb099aaafccee28598/src/gil.rs#L198-L205), which asserts that the Python interpreter has already been initialized. So it's probably an issue of trying to [acquire the GIL to call the `PyBuffer_Release` release callback](https://github.com/PyO3/pyo3/blob/cd5369c1a0d264db5db030bb099aaafccee28598/src/buffer.rs#L637) after the interpreter has already been finalized.

The unsafe code we're using is [`arrow_buffer::Buffer::from_custom_allocation`](https://github.com/kylebarron/arro3/blob/7649cba949c751f5051d6e1412f717043c619ecc/pyo3-arrow/src/buffer.rs#L255), which exhibits probably the same `unsafe` conditions as [`ptr.as_ref`](https://dev-doc.rust-lang.org/stable/core/ptr/struct.NonNull.html#method.as_ref).

Specifically:

> You must enforce Rust’s aliasing rules, since the returned lifetime 'a is arbitrarily chosen and does not necessarily reflect the actual lifetime of the data. In particular, while this reference exists, the memory the pointer points to must not get mutated (except inside UnsafeCell).

Maybe we're not upholding that?

Also this [part of the Python docs about finalization](https://docs.python.org/3/c-api/init.html#c.Py_FinalizeEx) may be relevant:

> **Bugs and caveats**: The destruction of modules and objects in modules is done in random order; this may cause destructors ([__del__()](https://docs.python.org/3/reference/datamodel.html#object.__del__) methods) to fail when they depend on other objects (even functions) or modules.

In this case, perhaps the issue is that pyarrow's destructor depends on arro3-core's destructor?

**Comment by jorisvandenbossche** [comment]
No idea if that is relevant here (didn't look in detail), but in something equivalent in PyArrow, we do check if Python is initialized before trying to dereference the python object (https://github.com/apache/arrow/blob/8a7224d21fb7ac1938cb039cc6dcfd38db94519e/python/pyarrow/src/arrow/python/common.h#L194-L199)

**Comment by kylebarron** [comment]
0.4.2 is building wheels and should be published to PyPI soon: https://github.com/kylebarron/arro3/actions/runs/11333818321
