### ISSUE TITLE
Pyo3 Arrow - support for Rust, rather than Python as the driver

### ISSUE THREAD

**Issue by pbower** [kylebarron/arro3#259]
Given the docs are focused on using Python as the driver, does pyo3-arrow in its current form support having rust as the driver calling python?
i.e. '[Using Python from Rust](https://pyo3.rs/v0.23.0/#using-python-from-rust)'

An example is round trip processing whereby python is used for access to certain libraries, but the main program is in rust.

note: this question relates to https://crates.io/crates/pyo3-arrow , which links back to this repo.

Thanks!

**Comment by kylebarron** [comment]
the Rust facing docs live here: https://docs.rs/pyo3-arrow/latest/pyo3_arrow/

**Comment by kylebarron** [comment]
Whether you use Rust to create Python bindings or whether you're using Python as the primary driver doesn't matter. In either case, you're using pyo3 to connect to the Python interpreter. 

pyo3-arrow manages the data conversion between Rust and Python. It's separate from where the "compute" happens. You can call Python functions from Rust if you'd like, and then call `extract` to a `pyo3-arrow` type whenever you're reading to move the data into Rust memory.
