### ISSUE TITLE
`RecordBatch` panics when requesting an out-of-bounds column

### ISSUE THREAD

**Issue by keewis** [kylebarron/arro3#271]
When fetching a out-of-bounds column using an integer index, `arro3` raises a `PanicException` where I'd expect an `IndexError`:
```python
from arro3.core import RecordBatch
import numpy as np

batch = RecordBatch.from_pydict({"lat": np.array([0, 1]), "lon": np.array([0, 1])})
batch[3]  # PanicException, should raise IndexError instead
```

The way I found this was by tuple-unpacking the columns, which is possible because python tries iterating over integer indices if [`__getitem__` but not `__iter__`](https://docs.python.org/3/glossary.html#term-iterable) is defined.

`arro3-core`: 0.4.3

**Comment by kylebarron** [comment]
This should be fixed in 0.4.4
