### ISSUE TITLE
No manylinux aarch64 wheels for version 0.4.4 release

### ISSUE THREAD

**Issue by cpcloud** [kylebarron/arro3#276]
These existed for 0.4.2, but don't seem to exist for 0.4.4. There are musllinux aarch64 wheels, but no manylinux aarch64 wheels.

Is this intentional?

**Comment by kylebarron** [comment]
Hmm looks like that happened here: https://github.com/kylebarron/arro3/pull/260/files#diff-75627befeafda60a526c116b32f6fdef9bf57bcf456f840d7592c1d6f13facb4R31

It might've been an underlying rust dependency upgrade or something similar that caused a compilation error.

arro3-core and arro3-compute have no issue compiling for linux aarch64, so the easiest PR would be to just refactor the matrix to enable those two. If you need arro3-io as well, then we have to fix the core issue. It might not be too hard (https://github.com/briansmith/ring/issues/1414#issuecomment-1055177218) but it always takes a while to iterate github actions until they pass

**Comment by cpcloud** [comment]
Ok, thanks!

Yeah, I would need them all to be built. These are transitive dependencies for an aarch64 linux Ibis development environment, and these are all transitive through lonboard I believe.

**Comment by cpcloud** [comment]
That said, this isn't critical, but it does break a long-working development setup that I have.

**Comment by kylebarron** [comment]
Thanks for the feedback; I'll check if I can get it to build

**Comment by kylebarron** [comment]
Looks like it's building correctly now. I pushed 0.4.5 and hopefully it should be on pypi soon
